'''
Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
'''

def fibonacci_sum(upperBound):
  fibDigs = [0,1];
  evenSum = 0;
  while(fibDigs[1] < upperBound):
    currentSum = fibDigs[0] + fibDigs[1]
    fibDigs[0] = fibDigs[1]
    fibDigs[1] = currentSum
    if(currentSum % 2 == 0):
      evenSum += currentSum
  return evenSum


print fibonacci_sum(4000000)